### PR TITLE
WIP: fix SCIP.jl for julia v0.7

### PR DESCRIPTION
**Pull request by leethargo**

### CODE REVIEW

**Comment by matbesancon** [comment]
what's the status on this? I think nightly can be replaced with 1.0 in travis and 0.7 in REQUIRE, this would also help people work with it on 0.7 and allow `Pkg.add("SCIP")` on Julia 1.0

**Comment by leethargo** [comment]
I am not actively working on this right now and am also stuck with 0.6 for my personal work, so this won't change in the near future.

It would make sense to write a new SCIP wrapper for MOI (rather than MathProgBase) and build it diretly on the SCIP C library (rather than the CSIP wrapper, see #28). That could be a whole separate project, then.

**Comment by matbesancon** [comment]
If you're ok I'll try to continue this one. JuMP 0.18.3 now works with Julia 1.0, I think this will be smoother to first upgrade to Julia 1.0 and then to MOI when it is finalized

**Comment by leethargo** [comment]
By all means go for it :+1:

**Comment by leethargo** [comment]
closed in favor of #70

**Pull request closed without merging**
