### PR TITLE
Support SCIP 7.0.0

### PR DESCRIPTION
**Pull request by rschwarz**

### CODE REVIEW

**Comment by rschwarz** [comment]
Still want to update Travis CI to use the newest SCIP, but the downloads are not ready yet?!

**Comment by fserra** [comment]
i have no idea why it still doesn't find it. Can one do an "ls" on `C:\scipoptdir\lib`?

**Comment by rschwarz** [comment]
It would be easiest to test this on a local Win machine first, I guess.

But yes, there is `Base.Filesystem.pwd()` and `Base.Filesystem.readdir()` in Julia. You can call `println( ... )` around these.

**Comment by fserra** [comment]
scip now needs tbb. and in windows is not finding the tbb.dll so we need to install it i guess. Apparently it works out of the box in linux

**Comment by rschwarz** [comment]
So, you mean that there is an additional dynamic library file, but it's missing from the installer?

This also implies that the error message from our `build.jl` is not really accurate, because in reality, the `scip.dll` file might exist, but `dlopen` fails because of some unresolved symbol or so?

**Comment by fserra** [comment]
yes I guess. So the `libscip.dll` was ok (I changed it to libscip.lib which is wrong). But I guess it identifies that `libscip.dll`  is not really the dll needed because it doesn't resolve everything. And yes, the error is not really transparent in saying where the file was not found or not useful.

**Comment by rschwarz** [comment]
@fserra: Windows now works with the new binaries, but OS X is failing when building from source, see https://travis-ci.org/github/SCIP-Interfaces/SCIP.jl/jobs/672463497#L208

By the way, I've previously tried to use pre-compiled binaries for OS X as well, but never got it to work, see #143.

**Comment by fserra** [comment]
yeah, i have no idea. I opened an issue in scip.

**Comment by rschwarz** [comment]
I tried again with preinstalled binaries of OS X, and it seems to be missing some dependencies:
https://travis-ci.org/github/SCIP-Interfaces/SCIP.jl/jobs/672477970#L218

**Pull request merged**
