### PR TITLE
implements getsolvetime

### LINKED ISSUE #17: implement getsolvetime
So I'm starting to run some experiments using SCIP, and I'm going to begin complaining about the missing methods that I need to get things working. First one is ``getsolvetime``.

### PR DESCRIPTION
**Pull request by fserra**
fix #17

### CODE REVIEW

**Comment by mlubin** [comment]
:+1: 
If you've tested it locally let's merge after travis passes.

**Comment by fserra** [comment]
If this is a valid test:
```julia
m = Model(Solver=SCIPSolver())
@variable(m, x)
solve(m)
getsolvetime(m)
```
Then it is good to merge

**Comment by mlubin** [comment]
Yes, it's a valid test (wouldn't hurt to add something to the unit tests).

**Comment by fserra** [comment]
how do you call getsolvetime from mathprogbase??

**Comment by mlubin** [comment]
``MathProgBase.getsolvetime``

**Comment by fserra** [comment]
Ok, this is a mess.

@leethargo we are freeing the transformed problem after the `SCIPsolve` in `CSIPsolve` and so the time obtained by `SCIPgetSolvingTime` is 0.

We have to do something about this,  like a function that needs to be called before modifying a problem.  
Otherwise, we would need to store also the solving time data in CSIP  :anguished: 

How would such a function be integrated? Would we need to call it basically in every method with a ! in its name?

**Comment by leethargo** [comment]
Was problem modification the only issue with the missing `freeTransform` after the `solve`?

**Comment by fserra** [comment]
I think yes

**Comment by leethargo** [comment]
I don't like it, but as with `PySCIPOpt`, it may be unavoidable if we don't want to restrict the feature set.

**Comment by leethargo** [comment]
@fserra : can you add your tests?

**Comment by fserra** [comment]
done

**Pull request merged**
