### PR TITLE
Prepare for MOI v0.9

### PR DESCRIPTION
**Pull request by rschwarz**
see https://github.com/JuliaOpt/MathOptInterface.jl/issues/736

### CODE REVIEW

**Comment by rschwarz** [comment]
This should be ready (passes the tests locally).

In fact, most of the changes in this commit are about implementing features that existed in MOI prior to v0.9, but that I learned about via the newly added tests and docs :man_student:

**Comment by rschwarz** [comment]
If we want to pass the tests in CI here, we should also change the version requirements in the `project.toml`, I think. I did not do so before, because the MOI version was not released yet.

**Comment by matbesancon** [comment]
From the failure, it looks like IpOpt needs to be upgraded first?

**Comment by rschwarz** [comment]
I don't know where you see something specific to IPOPT. The first failing log that I looked at in Travis only shows MOI unit test stuff.

In any case, SCIP.jl does not use IPOPT.jl, so it should not matter?

**Comment by matbesancon** [comment]
> I don't know where you see something specific to IPOPT.

Log on Travis:
https://travis-ci.org/SCIP-Interfaces/SCIP.jl/jobs/571451684#L318

Anyway the error seems linked to something else

**Comment by rschwarz** [comment]
> Log on Travis:

Yeah, but message from Ipopt always appears (once), even when everything passes. So it does not mean anything.

**Comment by rschwarz** [comment]
OK, the failing tests seem to point to real problems in SCIP, not an out-of-date `Project.toml`. Probably related to changes (tests) that were added to MOI after this PR was created. I will need to take a closer look later.

**Comment by rschwarz** [comment]
Unfortunately, the MINLPtests are failing with a `Pkg` dependency problem that I can't quite figure out from the [error message](https://travis-ci.org/SCIP-Interfaces/SCIP.jl/jobs/571798343#L329).

**Comment by matbesancon** [comment]
It seems to require JuMP, which has not been upgraded yet to MOI 0.9

**Comment by matbesancon** [comment]
@rschwarz there was a problem with the way the compats were specified, on #121 CEnum v0.2 is not compatible with the way we use it

**Comment by rschwarz** [comment]
So, we could merge this to `master` despite the failing `MINLPTests` (waiting for JuMP release, waiting for Julia bugfix), so that we can take care of the other open PRs.

But I don't know whether we should tag a new version for SCIP.jl before a compatible JuMP exists?

**Comment by matbesancon** [comment]
> So, we could merge this to master despite the failing MINLPTests

Maybe we can add an allowed failure on the travis script?

> But I don't know whether we should tag a new version for SCIP.jl before a compatible JuMP exists?

I think we should, officially, JuMP is just one of the interfaces on top of MOI, this should not be blocking for solvers

**Comment by rschwarz** [comment]
Good points. I'm not so clear about the Travis syntax on allowing that stage to fail. First attempt incoming...

**Pull request merged**
