### PR TITLE
add support for conic models

### PR DESCRIPTION
**Pull request by leethargo**

### CODE REVIEW

**Comment by fserra** [comment]
Do you why this was/is failing?

**Comment by leethargo** [comment]
I think Amazon's S3 had some issues yesterday that also broke Travis.

**Comment by fserra** [comment]
Oh, that explains why I couldn't look there

**Comment by leethargo** [comment]
Also, I'm not sure if any SOC specific tests exist, so it might just be the same testset as before, I just want to be sure.

**Pull request merged**
