### PR TITLE
build on macOS

### PR DESCRIPTION
**Pull request by chkwon**
For #42 

Instead of modifying `Makefile` in `CSIP`, I just added hard coded commands in `build.jl`. I was afraid that direct changes in `CSIP` may affect other linked packages for other languages.

### CODE REVIEW

**Comment by leethargo** [comment]
Thanks for your effort. I guess the instructions properly belong to the SCIP project itself. But I don't mind having them here.

I'm guessing that the failing test has nothing to do with the changes here?

**Comment by chkwon** [comment]
I'll write a Travis script for mac to make it sure.

**Comment by chkwon** [comment]
It seems that the error has  nothing to do with my changes. The error was:

```
Constraints with non-Array AbstractArrays: Error During Test
  Got an exception of type UndefVarError outside of a @test
  UndefVarError: OffsetArray not defined
   in macro expansion; at /home/travis/.julia/v0.5/JuMP/test/model.jl:982 [inlined]
   in macro expansion; at ./test.jl:674 [inlined]
   in macro expansion; at /home/travis/.julia/v0.5/JuMP/test/model.jl:979 [inlined]
   in macro expansion; at ./test.jl:674 [inlined]
   in anonymous at ./<missing>:?
   in include_from_node1(::String) at ./loading.jl:488 (repeats 2 times)
   in process_options(::Base.JLOptions) at ./client.jl:265
   in _start() at ./client.jl:321
Test Summary:                                                                                                                    | Pass  Error  Total
  Models                                                                                                                         |  269      1    270
  Check error cases                                                                                                              |    7             7
  Warning on non-symbol variable names                                                                                           |              No tests
  Performance warnings                                                                                                           |              No tests
  Test printing a model                                                                                                          |   84            84
  Quadratic MPS writer                                                                                                           |   21            21
  Solving a MILP with SCIP.SCIPSolver(Any["display/verblevel",0,"limits/time",100.0])                                            |   11            11
  Solving an LP (Min) with GLPKMathProgInterface.GLPKInterfaceLP.GLPKSolverLP(false,:Simplex,Any[])                              |   19            19
  Test solving an LP (Max) with GLPKMathProgInterface.GLPKInterfaceLP.GLPKSolverLP(false,:Simplex,Any[])                         |   19            19
  Test binary variable handling with SCIP.SCIPSolver(Any["display/verblevel",0,"limits/time",100.0])                             |    2             2
  Test model copying                                                                                                             |   30            30
  Test extension copy                                                                                                            |    3             3
  Test variable/model 'hygiene'                                                                                                  |    5             5
  Test NaN checking                                                                                                              |    3             3
  Test column-wise modeling with GLPKMathProgInterface.GLPKInterfaceLP.GLPKSolverLP(false,:Simplex,Any[])                        |    9             9
  [model] Test all MPS paths                                                                                                     |              No tests
  Test all LP paths                                                                                                              |    1             1
  Test fixed variables don't leak through MPB with GLPKMathProgInterface.GLPKInterfaceLP.GLPKSolverLP(false,:Simplex,Any[])      |    5             5
  Fixed variables with SCIP.SCIPSolver(Any["display/verblevel",0,"limits/time",100.0])                                           |    1             1
  Test SOS constraints with SCIP.SCIPSolver(Any["display/verblevel",0,"limits/time",100.0])                                      |   11            11
  Test vectorized model creation                                                                                                 |    3             3
  Test MIQP vectorization                                                                                                        |    2             2
  Test setsolver                                                                                                                 |    5             5
  [model] Setting solve hook                                                                                                     |    2             2
  Setting print hook                                                                                                             |    1             1
  Test linearindex                                                                                                               |    5             5
  Test LinearConstraint from ConstraintRef                                                                                       |    1             1
  Test getvalue on OneIndexedArrays                                                                                              |    2             2
  Relaxation keyword argument to solve (w/ SOS constraints) with SCIP.SCIPSolver(Any["display/verblevel",0,"limits/time",100.0]) |    8             8
  Unrecognized keyword argument to solve                                                                                         |    1             1
  Solve MIP relaxation with continuous solvers                                                                                   |    2             2
  Nonliteral exponents in @constraint                                                                                            |    4             4
  sets used as indexsets in JuMPArray                                                                                            |    1             1
  [model] .^ broadcasting                                                                                                        |    1             1
  Constraints with non-Array AbstractArrays                                                                                      |           1      1
ERROR: LoadError: LoadError: Some tests did not pass: 269 passed, 0 failed, 1 errored, 0 broken.
 in finish(::Base.Test.DefaultTestSet) at ./test.jl:498
 in macro expansion; at ./test.jl:681 [inlined]
 in anonymous at ./<missing>:?
 in include_from_node1(::String) at ./loading.jl:488 (repeats 2 times)
 in process_options(::Base.JLOptions) at ./client.jl:265
 in _start() at ./client.jl:321
while loading /home/travis/.julia/v0.5/JuMP/test/model.jl, in expression starting on line 34
while loading /home/travis/.julia/v0.5/SCIP/test/runtests.jl, in expression starting on line 43
================================[ ERROR: SCIP ]=================================
failed process: Process(`/home/travis/julia/bin/julia -Cx86-64 -J/home/travis/julia/lib/julia/sys.so --compile=yes --depwarn=yes --check-bounds=yes --code-coverage=user --inline=no --color=no --compilecache=yes /home/travis/.julia/v0.5/SCIP/test/runtests.jl`, ProcessExited(1)) [1]
================================================================================
```

**Comment by chkwon** [comment]
I obtain the same error in my local machine with `Pkg.test("SCIP")`. To reassure, you may re-run the travis test with the master branch.

**Comment by leethargo** [comment]
Yes, the failing test is because of a missing dependency on OffsetArrays that was introduced in JuMP recently. I'll fix it in a minute.

**Comment by chkwon** [comment]
@leethargo Thanks for the merge. Hope that you can tag a new version, so that macOS users can add the interface easily.

**Comment by leethargo** [comment]
I guess we will update to the new version of SCIP (4.0) first and then release again.

**Pull request merged**
