### PR TITLE
implement solver-independent parameters and fix some compat issues

### PR DESCRIPTION
**Pull request by mlubin**
CC @chriscoey

### CODE REVIEW

**Comment by leethargo** [comment]
So there aren't any more solver-independent parameters in MPB right now? I assume that most solvers support limits on nodes, solutions and gap (although the definitions of gap might not agree).

**Comment by mlubin** [comment]
That's all the parameters for now. "I assume" is a lot easier to say than going through all the solvers to make sure that their definitions of these parameters are consistent. We won't add parameters until that work is done by someone who's sufficiently motivated.

**Comment by mlubin** [comment]
@leethargo, safe to tag a new release?

**Comment by leethargo** [comment]
Sure, I remember a discussion of gap and the "Cplex definition" vs the "SCIP definition".

Go ahead with the release, I don't have any changes lined up.

**Pull request merged**
