### PR TITLE
Ck/mac patch 400 xcode82

### PR DESCRIPTION
**Pull request by chkwon**
`more_test.jl` fails both in my local machine and in travis.

```
INFO: Testing SCIP
signal (11): Segmentation fault: 11
while loading /Users/travis/.julia/v0.5/SCIP/test/more_tests.jl, in expression starting on line 2
_ZN6soplex9CLUFactor8remaxRowEii at /Users/travis/build/chkwon/SCIP.jl/scipoptsuite-4.0.0/lib/libscipopt.dylib (unknown line)
_ZN6soplex9CLUFactor12forestUpdateEiPdiPi at /Users/travis/build/chkwon/SCIP.jl/scipoptsuite-4.0.0/lib/libscipopt.dylib (unknown line)
_ZN6soplex9SLUFactor6changeEiRKNS_11SVectorBaseIdEEPKNS_12SSVectorBaseIdEE at /Users/travis/build/chkwon/SCIP.jl/scipoptsuite-4.0.0/lib/libscipopt.dylib (unknown line)
_ZN6soplex8SPxBasis6changeEiRNS_5SPxIdEPKNS_11SVectorBaseIdEEPKNS_12SSVectorBaseIdEE at /Users/travis/build/chkwon/SCIP.jl/scipoptsuite-4.0.0/lib/libscipopt.dylib (unknown line)
_ZN6soplex9SPxSolver5leaveEib at /Users/travis/build/chkwon/SCIP.jl/scipoptsuite-4.0.0/lib/libscipopt.dylib (unknown line)
_ZN6soplex9SPxSolver5solveEv at /Users/travis/build/chkwon/SCIP.jl/scipoptsuite-4.0.0/lib/libscipopt.dylib (unknown line)
_ZN6soplex6SoPlex31_solveRealLPAndRecordStatisticsEv at /Users/travis/build/chkwon/SCIP.jl/scipoptsuite-4.0.0/lib/libscipopt.dylib (unknown line)
_ZN6soplex6SoPlex23_preprocessAndSolveRealEb at /Users/travis/build/chkwon/SCIP.jl/scipoptsuite-4.0.0/lib/libscipopt.dylib (unknown line)
_ZN6soplex6SoPlex13_optimizeRealEv at /Users/travis/build/chkwon/SCIP.jl/scipoptsuite-4.0.0/lib/libscipopt.dylib (unknown line)
_ZN6soplex6SoPlex8optimizeEv at /Users/travis/build/chkwon/SCIP.jl/scipoptsuite-4.0.0/lib/libscipopt.dylib (unknown line)
_ZN7SPxSCIP8trySolveEb at /Users/travis/build/chkwon/SCIP.jl/scipoptsuite-4.0.0/lib/libscipopt.dylib (unknown line)
_ZL8spxSolveP8SCIP_LPi at /Users/travis/build/chkwon/SCIP.jl/scipoptsuite-4.0.0/lib/libscipopt.dylib (unknown line)
lpAlgorithm at /Users/travis/build/chkwon/SCIP.jl/scipoptsuite-4.0.0/lib/libscipopt.dylib (unknown line)
lpSolveStable at /Users/travis/build/chkwon/SCIP.jl/scipoptsuite-4.0.0/lib/libscipopt.dylib (unknown line)
lpSolve at /Users/travis/build/chkwon/SCIP.jl/scipoptsuite-4.0.0/lib/libscipopt.dylib (unknown line)
SCIPlpSolveAndEval at /Users/travis/build/chkwon/SCIP.jl/scipoptsuite-4.0.0/lib/libscipopt.dylib (unknown line)
propAndSolve at /Users/travis/build/chkwon/SCIP.jl/scipoptsuite-4.0.0/lib/libscipopt.dylib (unknown line)
SCIPsolveCIP at /Users/travis/build/chkwon/SCIP.jl/scipoptsuite-4.0.0/lib/libscipopt.dylib (unknown line)
SCIPsolve at /Users/travis/build/chkwon/SCIP.jl/scipoptsuite-4.0.0/lib/libscipopt.dylib (unknown line)
CSIPsolve at /Users/travis/.julia/v0.5/SCIP/deps/usr/lib/libcsip.dylib (unknown line)
_solve at /Users/travis/.julia/v0.5/SCIP/src/wrapper.jl:130
optimize! at /Users/travis/.julia/v0.5/SCIP/src/mpb_interface.jl:59
macro expansion; at /Users/travis/.julia/v0.5/SCIP/test/more_tests.jl:17 [inlined]
macro expansion; at ./test.jl:674 [inlined]
anonymous at ./<missing> (unknown line)
unknown function (ip: 0x3198b4bbf)
jl_call_method_internal at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/./julia_internal.h:210 [inlined]
jl_toplevel_eval_flex at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/toplevel.c:569
jl_parse_eval_all at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/ast.c:717
jl_load at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/toplevel.c:596 [inlined]
jl_load_ at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/toplevel.c:605
include_from_node1 at ./loading.jl:488
jlcall_include_from_node1_20312 at /Users/travis/julia/lib/julia/sys.dylib (unknown line)
jl_call_method_internal at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/./julia_internal.h:210 [inlined]
jl_apply_generic at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/gf.c:1950
do_call at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/interpreter.c:66
eval at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/interpreter.c:190
jl_toplevel_eval_flex at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/toplevel.c:558
jl_parse_eval_all at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/ast.c:717
jl_load at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/toplevel.c:596 [inlined]
jl_load_ at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/toplevel.c:605
include_from_node1 at ./loading.jl:488
jlcall_include_from_node1_20312 at /Users/travis/julia/lib/julia/sys.dylib (unknown line)
jl_call_method_internal at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/./julia_internal.h:210 [inlined]
jl_apply_generic at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/gf.c:1950
process_options at ./client.jl:265
_start at ./client.jl:321
jlcall__start_21657 at /Users/travis/julia/lib/julia/sys.dylib (unknown line)
jl_call_method_internal at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/./julia_internal.h:210 [inlined]
jl_apply_generic at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/gf.c:1950
true_main at /Users/travis/julia/bin/julia (unknown line)
main at /Users/travis/julia/bin/julia (unknown line)
Allocations: 1802498 (Pool: 1801559; Big: 939); GC: 0
================================[ ERROR: SCIP ]=================================
failed process: Process(`/Users/travis/julia/bin/julia -Ccore2 -J/Users/travis/julia/lib/julia/sys.dylib --compile=yes --depwarn=yes --check-bounds=yes --code-coverage=user --inline=no --color=no --compilecache=yes /Users/travis/.julia/v0.5/SCIP/test/runtests.jl`, ProcessSignaled(11)) [0]
================================================================================
```

Not sure what to do with this error. 

In my local machine, I tested each test instance:

```
include("more_tests.jl") x
include("mixintprog.jl") o
include(joinpath(Pkg.dir("JuMP"),"test","model.jl")) x
include(joinpath(Pkg.dir("JuMP"),"test","probmod.jl")) o
include(joinpath(Pkg.dir("JuMP"),"test","qcqpmodel.jl")) x
include(joinpath(Pkg.dir("JuMP"),"test","callback.jl"))  x
include(joinpath(Pkg.dir("JuMP"),"test","nonlinear.jl")) x
```

`x` means `signal (11): Segmentation fault: 11`.
`o` means Test Passed.

### CODE REVIEW

**Comment by chkwon** [comment]
FYI


```
using SCIP, JuMP
m = Model(solver=SCIPSolver())
@variable(m, x>=0)
@variable(m, y>=0)
@objective(m, Min, x - 2*y)
@constraint(m, x + y <= 3)
solve(m)
```
==> This works.


```
using SCIP, JuMP
m = Model(solver=SCIPSolver())
@variable(m, x>=0)
@variable(m, y>=0)
@objective(m, Min, x^2 - 2*y)
@constraint(m, x + y^2 <= 3)
solve(m)
```
==> This works.


```
using SCIP, JuMP
m = Model(solver=SCIPSolver())
@variable(m, x>=0)
@variable(m, y>=0, Int)
@objective(m, Min, x^2 - 2*y)
@constraint(m, x + y^2 <= 3)
solve(m)
```
==> This works.


```
using SCIP, JuMP
m = Model(solver=SCIPSolver())
@variable(m, x>=0)
@variable(m, y>=0)
@objective(m, Min, x^2 + 2*y^2)
@constraint(m, x^2 + y^2 <= 3)
solve(m)
```
==> This works.


```
using SCIP, JuMP
m = Model(solver=SCIPSolver())
@variable(m, x>=0)
@variable(m, y>=0)
@objective(m, Min, x^2 - 2*y^2)
@constraint(m, x^2 + y^2 <= 3)
solve(m)
```
==> This does NOT work. (Segmentation fault).

**Comment by chkwon** [comment]
I just realized that SCIP 4.0.0 does not provide executables for macOS yet. They provided executables for SCIP 3.2.1 though.

**Comment by fserra** [comment]
what do you mean??

**Comment by chkwon** [comment]
@fserra Perhaps, SCIP 4.0.0 is not sufficiently tested in macOS? 

Maybe related: https://github.com/SCIP-Interfaces/PySCIPOpt/issues/29#issuecomment-285745232

[[SCIP] SCIPoptsuite 4.0.0 shared library installation broken on MacOS X](http://listserv.zib.de/pipermail/scip/2017-March/003017.html)

**Comment by leethargo** [comment]
The issue on the mailing list seems to be related to the linking steps to get your `.dylib` file. But what you experience now is segfaults deep in the LP solving, so that is a lot more worrisome.

**Comment by fserra** [comment]
@leethargo, I wasn't able to reproduce the segfault with
```Julia
using SCIP, JuMP
m = Model(solver=SCIPSolver())
@variable(m, x>=0)
@variable(m, y>=0)
@objective(m, Min, x^2 - 2*y^2)
@constraint(m, x^2 + y^2 <= 3)
solve(m)
```
were you able to reproduce it?

**Comment by leethargo** [comment]
I thought the segfault only occurs on OS X?

**Comment by chkwon** [comment]
Yes, this problem is only for macOS. It might be either because of the way I compiled the library or because of the SCIP source code itself. Since some JuMP models work and some don't, this is pretty confusing.

**Comment by leethargo** [comment]
Do the CSIP tests run with on OS X with the new SCIP?

**Comment by chkwon** [comment]
@leethargo Good question. The answer is no.

Again, after creating a symbolic link named `libscipopt-4.0.0.darwin.x86_64.gnu.opt.so`, instead of just `libscipopt.so`, I was able to run `make test`:

```
:~/.julia/v0.5/SCIP/deps/src/CSIP-0.4.0$ make test
make[1]: `/Users/chkwon/.julia/v0.5/SCIP/deps/src/CSIP-0.4.0/test/test' is up to date.
/Users/chkwon/.julia/v0.5/SCIP/deps/src/CSIP-0.4.0/test/test 
Running tests...
  test_lp
  test_mip
  test_mip2
  test_mip3
  test_socp
make: *** [test] Segmentation fault: 11
```

**Comment by leethargo** [comment]
This good, because it would give us some small piece of C code that should be easier for the SCIP devs to debug.

**Comment by mattmilten** [comment]
I just stumbled upon this issue again. Did you already manage to pin the problem down somehow?

**Comment by chkwon** [comment]
@mattmilten No. I guess though, it is a SCIP problem, not CSIP.

**Comment by leethargo** [comment]
@chkwon: Does it mean that SCIP.jl `master` works for you now, based on SCIP 5.0.0?

**Comment by chkwon** [comment]
@leethargo Well, I tried once to compile SCIP 5.0.0 without success. I closed this *pull request* since it does not make any sense anyway. Still #46 is open.

**Pull request closed without merging**
